services:

  # Microsserviços
  credor-service:
    container_name: credor-service
    image: gabriellagrota/credor-service:latest
    restart: always
    build: ./services/credor-service
    working_dir: /
    environment:
      TZ: America/Sao_Paulo
      DB_URL: postgresql://credor-db:5432/credordb
      DB_USERNAME: postgres
      DB_PASSWORD: root
    ports:
      - "8081:8081"
    command: mvn spring-boot:run
    depends_on:
      - credor-db
    networks:
      - app-network

  devedor-service:
    container_name: devedor-service
    image: gabriellagrota/devedor-service:latest
    restart: always
    build: ./services/devedor-service
    working_dir: /
    environment:
      TZ: America/Sao_Paulo
      DB_URL: postgresql://devedor-db:5432/devedordb
      DB_USERNAME: postgres
      DB_PASSWORD: root
    ports:
      - "8082:8082"
    command: mvn spring-boot:run
    depends_on:
      - devedor-db
    networks:
      - app-network

  emprestimo-service:
    container_name: emprestimo-service
    image: gabriellagrota/emprestimo-service:latest
    restart: always
    build: ./services/emprestimo-service
    working_dir: /
    environment:
      TZ: America/Sao_Paulo
      DB_URL: postgresql://emprestimo-db:5432/emprestimodb
      DB_USERNAME: postgres
      DB_PASSWORD: root
    ports:
      - "8083:8083"
    command: mvn spring-boot:run
    depends_on:
      - emprestimo-db
    networks:
      - app-network

  proposta-service:
    container_name: proposta-service
    image: gabriellagrota/proposta-service:latest
    restart: always
    build: ./services/proposta-service
    working_dir: /
    environment:
      TZ: America/Sao_Paulo
      DB_URL: postgresql://proposta-db:5432/propostadb
      DB_USERNAME: postgres
      DB_PASSWORD: root
    ports:
      - "8084:8084"
    command: mvn spring-boot:run
    depends_on:
      - proposta-db
    networks:
      - app-network

  # Bancos de Dados PostgreSQL
  auth-db:
    image: postgres:15
    container_name: auth-db
    environment:
      POSTGRES_DB: authdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5433:5432"
    networks:
      - app-network

  credor-db:
    image: postgres:15
    container_name: credor-db
    restart: always
    environment:
      POSTGRES_DB: credordb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5434:5432"
    networks:
      - app-network
    ##    volumes:
    ##      - postgres_data:/var/lib/postgresql/data

  devedor-db:
    image: postgres:15
    container_name: devedor-db
    environment:
      POSTGRES_DB: devedordb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5435:5432"
    networks:
      - app-network

  emprestimo-db:
    image: postgres:15
    container_name: emprestimo-db
    environment:
      POSTGRES_DB: emprestimodb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5436:5432"
    networks:
      - app-network

  proposta-db:
    image: postgres:15
    container_name: proposta-db
    environment:
      POSTGRES_DB: propostadb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5437:5432"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

#volumes:
#  postgres_data:
#    driver: local