server:
  port: 8081

spring:
  application:
    name: credor-service

  # Configuracoes de banco de dados
  jpa:
    show-sql: false
    generate-ddl: true
    hibernate.ddl-auto: update
    properties:
      hibernate:
        generate_statistics: true
        format_sql: true
  datasource:
    url: jdbc:${DB_URL}?useTimezone=true&serverTimezone=UTC&useSSL=false
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 30000
      minimum-idle: 10
      maximum-pool-size: 10
      idle-timeout: 600000
      max-lifetime: 1800000

management:
  endpoints:
    web:
      exposure:
        include: health, metrics, resilience4j
  endpoint:
    health:
      show-details: always

resilience4j:
  circuitbreaker:
    instances:
      criaCredor:
        slidingWindowSize: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
        minimumNumberOfCalls: 5

# Configuracoes do Swagger
springdoc:
  swagger-ui:
    disable-swagger-default-url: true
    path: /documentacao-api
    operationsSorter: method
    tagsSorter: alpha
swagger:
  username: ${SWAGGER_USERNAME}
  password: ${SWAGGER_PASSWORD}